# Copyright (c) the IW4x authors (see the AUTHORS file).
# SPDX-License-Identifier: GPL-3.0-only WITH AdditionRef-IW4x-Exception-1.1

intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

# The utility declarations and the contract checking facility come from
# libobe.
#
import intf_libs = libobe%lib{obe}

lib{xle}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBXLE_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBXLE_SHARED_BUILD

# Export options.
#
lib{xle}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{xle}: cxx.export.poptions += -DLIBXLE_STATIC
libs{xle}: cxx.export.poptions += -DLIBXLE_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{xle}: bin.lib.version = "-$version.project_id"
else
  lib{xle}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libxle/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libxle/
  install.subdirs = true
}
