// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

// Begin prologue.
//
//
// End prologue.

#include <cassert>

namespace xle
{
  namespace cli
  {
    // usage_para
    //
    inline usage_para::
    usage_para (value v)
    : v_ (v)
    {
    }

    // unknown_mode
    //
    inline unknown_mode::
    unknown_mode (value v)
    : v_ (v)
    {
    }

    // exception
    //
    inline ::std::ostream&
    operator<< (::std::ostream& os, const exception& e)
    {
      e.print (os);
      return os;
    }

    // unknown_option
    //
    inline unknown_option::
    unknown_option (const std::string& option)
    : option_ (option)
    {
    }

    inline const std::string& unknown_option::
    option () const
    {
      return option_;
    }

    // unknown_argument
    //
    inline unknown_argument::
    unknown_argument (const std::string& argument)
    : argument_ (argument)
    {
    }

    inline const std::string& unknown_argument::
    argument () const
    {
      return argument_;
    }

    // missing_value
    //
    inline missing_value::
    missing_value (const std::string& option)
    : option_ (option)
    {
    }

    inline const std::string& missing_value::
    option () const
    {
      return option_;
    }

    // invalid_value
    //
    inline invalid_value::
    invalid_value (const std::string& option,
                   const std::string& value,
                   const std::string& message)
    : option_ (option),
      value_ (value),
      message_ (message)
    {
    }

    inline const std::string& invalid_value::
    option () const
    {
      return option_;
    }

    inline const std::string& invalid_value::
    value () const
    {
      return value_;
    }

    inline const std::string& invalid_value::
    message () const
    {
      return message_;
    }

    // file_io_failure
    //
    inline file_io_failure::
    file_io_failure (const std::string& file)
    : file_ (file)
    {
    }

    inline const std::string& file_io_failure::
    file () const
    {
      return file_;
    }

    // unmatched_quote
    //
    inline unmatched_quote::
    unmatched_quote (const std::string& argument)
    : argument_ (argument)
    {
    }

    inline const std::string& unmatched_quote::
    argument () const
    {
      return argument_;
    }

    // argv_scanner
    //
    inline argv_scanner::
    argv_scanner (int& argc,
                  char** argv,
                  bool erase,
                  std::size_t sp)
    : start_position_ (sp + 1),
      i_ (1),
      argc_ (argc),
      argv_ (argv),
      erase_ (erase)
    {
    }

    inline argv_scanner::
    argv_scanner (int start,
                  int& argc,
                  char** argv,
                  bool erase,
                  std::size_t sp)
    : start_position_ (sp + static_cast<std::size_t> (start)),
      i_ (start),
      argc_ (argc),
      argv_ (argv),
      erase_ (erase)
    {
    }

    inline int argv_scanner::
    end () const
    {
      return i_;
    }

    // argv_file_scanner
    //
    inline argv_file_scanner::
    argv_file_scanner (int& argc,
                       char** argv,
                       const std::string& option,
                       bool erase,
                       std::size_t sp)
    : argv_scanner (argc, argv, erase, sp),
      option_ (option),
      options_ (&option_info_),
      options_count_ (1),
      i_ (1),
      skip_ (false)
    {
      option_info_.option = option_.c_str ();
      option_info_.search_func = 0;
    }

    inline argv_file_scanner::
    argv_file_scanner (int start,
                       int& argc,
                       char** argv,
                       const std::string& option,
                       bool erase,
                       std::size_t sp)
    : argv_scanner (start, argc, argv, erase, sp),
      option_ (option),
      options_ (&option_info_),
      options_count_ (1),
      i_ (1),
      skip_ (false)
    {
      option_info_.option = option_.c_str ();
      option_info_.search_func = 0;
    }

    inline argv_file_scanner::
    argv_file_scanner (const std::string& file,
                       const std::string& option,
                       std::size_t sp)
    : argv_scanner (0, zero_argc_, 0, sp),
      option_ (option),
      options_ (&option_info_),
      options_count_ (1),
      i_ (1),
      skip_ (false)
    {
      option_info_.option = option_.c_str ();
      option_info_.search_func = 0;

      load (file);
    }

    inline argv_file_scanner::
    argv_file_scanner (int& argc,
                       char** argv,
                       const option_info* options,
                       std::size_t options_count,
                       bool erase,
                       std::size_t sp)
    : argv_scanner (argc, argv, erase, sp),
      options_ (options),
      options_count_ (options_count),
      i_ (1),
      skip_ (false)
    {
    }

    inline argv_file_scanner::
    argv_file_scanner (int start,
                       int& argc,
                       char** argv,
                       const option_info* options,
                       std::size_t options_count,
                       bool erase,
                       std::size_t sp)
    : argv_scanner (start, argc, argv, erase, sp),
      options_ (options),
      options_count_ (options_count),
      i_ (1),
      skip_ (false)
    {
    }

    inline argv_file_scanner::
    argv_file_scanner (const std::string& file,
                       const option_info* options,
                       std::size_t options_count,
                       std::size_t sp)
    : argv_scanner (0, zero_argc_, 0, sp),
      options_ (options),
      options_count_ (options_count),
      i_ (1),
      skip_ (false)
    {
      load (file);
    }
  }
}

namespace xle
{
  // options
  //

  inline const bool& options::
  help () const
  {
    return this->help_;
  }

  inline const bool& options::
  version () const
  {
    return this->version_;
  }

  inline const std::string& options::
  options_file () const
  {
    return this->options_file_;
  }

  inline bool options::
  options_file_specified () const
  {
    return this->options_file_specified_;
  }

  inline const bool& options::
  v () const
  {
    return this->v_;
  }

  inline const bool& options::
  V () const
  {
    return this->V_;
  }

  inline const bool& options::
  quiet () const
  {
    return this->quiet_;
  }

  inline const std::uint16_t& options::
  verbose () const
  {
    return this->verbose_;
  }

  inline bool options::
  verbose_specified () const
  {
    return this->verbose_specified_;
  }

  inline const std::string& options::
  address () const
  {
    return this->address_;
  }

  inline bool options::
  address_specified () const
  {
    return this->address_specified_;
  }

  inline const std::uint16_t& options::
  port () const
  {
    return this->port_;
  }

  inline bool options::
  port_specified () const
  {
    return this->port_specified_;
  }

  inline const std::string& options::
  tls_certificate () const
  {
    return this->tls_certificate_;
  }

  inline bool options::
  tls_certificate_specified () const
  {
    return this->tls_certificate_specified_;
  }

  inline const std::string& options::
  tls_key () const
  {
    return this->tls_key_;
  }

  inline bool options::
  tls_key_specified () const
  {
    return this->tls_key_specified_;
  }

  inline const bool& options::
  print_endpoint () const
  {
    return this->print_endpoint_;
  }

  inline const std::string& options::
  db_name () const
  {
    return this->db_name_;
  }

  inline bool options::
  db_name_specified () const
  {
    return this->db_name_specified_;
  }

  inline const std::string& options::
  db_user () const
  {
    return this->db_user_;
  }

  inline bool options::
  db_user_specified () const
  {
    return this->db_user_specified_;
  }

  inline const std::string& options::
  db_password () const
  {
    return this->db_password_;
  }

  inline bool options::
  db_password_specified () const
  {
    return this->db_password_specified_;
  }

  inline const std::string& options::
  db_host () const
  {
    return this->db_host_;
  }

  inline bool options::
  db_host_specified () const
  {
    return this->db_host_specified_;
  }

  inline const std::uint16_t& options::
  db_port () const
  {
    return this->db_port_;
  }

  inline bool options::
  db_port_specified () const
  {
    return this->db_port_specified_;
  }

  inline const std::size_t& options::
  db_max_connections () const
  {
    return this->db_max_connections_;
  }

  inline bool options::
  db_max_connections_specified () const
  {
    return this->db_max_connections_specified_;
  }

  inline const std::size_t& options::
  db_retry () const
  {
    return this->db_retry_;
  }

  inline bool options::
  db_retry_specified () const
  {
    return this->db_retry_specified_;
  }

  inline const bool& options::
  migrate () const
  {
    return this->migrate_;
  }
}

// Begin epilogue.
//
//
// End epilogue.
