// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include <libxle/model-odb.hxx>

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/view-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>
#include <odb/pgsql/view-result.hxx>

namespace odb
{
  // relationship_key
  //

  bool access::composite_value_traits< ::xle::relationship_key, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // owner
    //
    t[0UL] = 0;

    // target
    //
    t[1UL] = 0;

    return grew;
  }

  void access::composite_value_traits< ::xle::relationship_key, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (b);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);
    ODB_POTENTIALLY_UNUSED (n);

    // owner
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.owner_value;
    b[n].is_null = &i.owner_null;
    n++;

    // target
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.target_value;
    b[n].is_null = &i.target_null;
    n++;
  }

  bool access::composite_value_traits< ::xle::relationship_key, id_pgsql >::
  init (image_type& i,
        const value_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // owner
    //
    {
      ::xle::xuid const& v =
        o.owner;

      bool is_null (false);

      // From model.hxx:50:12
      ::uint64_t const& vt =
        std::to_underlying (v);

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_image (
        i.owner_value, is_null, vt);
      i.owner_null = is_null;
    }

    // target
    //
    {
      ::xle::xuid const& v =
        o.target;

      bool is_null (false);

      // From model.hxx:50:12
      ::uint64_t const& vt =
        std::to_underlying (v);

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_image (
        i.target_value, is_null, vt);
      i.target_null = is_null;
    }

    return grew;
  }

  void access::composite_value_traits< ::xle::relationship_key, id_pgsql >::
  init (value_type& o,
        const image_type&  i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // owner
    //
    {
      ::xle::xuid& v =
        o.owner;

      ::uint64_t vt;

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.owner_value,
        i.owner_null);

      // From model.hxx:50:12
      v = xle::xuid 
      {
         (vt) 
      };
    }

    // target
    //
    {
      ::xle::xuid& v =
        o.target;

      ::uint64_t vt;

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.target_value,
        i.target_null);

      // From model.hxx:50:12
      v = xle::xuid 
      {
         (vt) 
      };
    }
  }

  // relationship_record
  //

  const char access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  persist_statement_name[] = "persist_xle_relationship_record";

  const char access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  find_statement_name[] = "find_xle_relationship_record";

  const char access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  update_statement_name[] = "update_xle_relationship_record";

  const char access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  erase_statement_name[] = "erase_xle_relationship_record";

  const char access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  query_statement_name[] = "query_xle_relationship_record";

  const char access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  erase_query_statement_name[] = "erase_query_xle_relationship_record";

  const unsigned int access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::bool_oid,
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int8_oid,
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::bool_oid,
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::int8_oid
  };

  struct access::object_traits_impl< ::xle::relationship_record, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::xle::relationship_record, id_pgsql >::id_type
  access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      composite_value_traits< ::xle::relationship_key, id_pgsql >::init (
        id,
        i.id_value,
        db);
    }

    return id;
  }

  bool access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    if (composite_value_traits< ::xle::relationship_key, id_pgsql >::grow (
          i.id_value, t + 0UL))
      grew = true;

    // favorite
    //
    t[2UL] = 0;

    // added
    //
    t[3UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id
    //
    if (sk != statement_update)
    {
      composite_value_traits< ::xle::relationship_key, id_pgsql >::bind (
        b + n, i.id_value, sk);
      n += 2UL;
    }

    // favorite
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.favorite_value;
    b[n].is_null = &i.favorite_null;
    n++;

    // added
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.added_value;
    b[n].is_null = &i.added_null;
    n++;
  }

  void access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    pgsql::statement_kind sk (pgsql::statement_select);
    composite_value_traits< ::xle::relationship_key, id_pgsql >::bind (
      b + n, i.id_value, sk);
  }

  bool access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // id
    //
    if (sk == statement_insert)
    {
      ::xle::relationship_key const& v =
        o.id;

      composite_value_traits< ::xle::relationship_key, id_pgsql >::init (
        i.id_value,
        v,
        sk);
    }

    // favorite
    //
    {
      bool const& v =
        o.favorite;

      bool is_null (false);

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_image (
        i.favorite_value, is_null, v);
      i.favorite_null = is_null;
    }

    // added
    //
    {
      ::xle::timestamp const& v =
        o.added;

      bool is_null (false);

      // From model.hxx:58:12
      ::int64_t const& vt =
        std::chrono::duration_cast < std::chrono::nanoseconds > ((v).time_since_epoch ()).count ();

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_image (
        i.added_value, is_null, vt);
      i.added_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      ::xle::relationship_key& v =
        o.id;

      composite_value_traits< ::xle::relationship_key, id_pgsql >::init (
        v,
        i.id_value,
        db);
    }

    // favorite
    //
    {
      bool& v =
        o.favorite;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.favorite_value,
        i.favorite_null);
    }

    // added
    //
    {
      ::xle::timestamp& v =
        o.added;

      ::int64_t vt;

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.added_value,
        i.added_null);

      // From model.hxx:58:12
      v = xle::timestamp (std::chrono::duration_cast < xle::duration > (std::chrono::nanoseconds (vt)));
    }
  }

  void access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    pgsql::statement_kind sk (pgsql::statement_select);
    {
      composite_value_traits< ::xle::relationship_key, id_pgsql >::init (
        i.id_value,
        id,
        sk);
    }
  }

  const char access::object_traits_impl< ::xle::relationship_record, id_pgsql >::persist_statement[] =
  "INSERT INTO \"relationship\" "
  "(\"owner\", "
  "\"target\", "
  "\"favorite\", "
  "\"added\") "
  "VALUES "
  "($1, $2, $3, $4)";

  const char access::object_traits_impl< ::xle::relationship_record, id_pgsql >::find_statement[] =
  "SELECT "
  "\"relationship\".\"owner\", "
  "\"relationship\".\"target\", "
  "\"relationship\".\"favorite\", "
  "\"relationship\".\"added\" "
  "FROM \"relationship\" "
  "WHERE \"relationship\".\"owner\"=$1 AND \"relationship\".\"target\"=$2";

  const char access::object_traits_impl< ::xle::relationship_record, id_pgsql >::update_statement[] =
  "UPDATE \"relationship\" "
  "SET "
  "\"favorite\"=$1, "
  "\"added\"=$2 "
  "WHERE \"owner\"=$3 AND \"target\"=$4";

  const char access::object_traits_impl< ::xle::relationship_record, id_pgsql >::erase_statement[] =
  "DELETE FROM \"relationship\" "
  "WHERE \"owner\"=$1 AND \"target\"=$2";

  const char access::object_traits_impl< ::xle::relationship_record, id_pgsql >::query_statement[] =
  "SELECT "
  "\"relationship\".\"owner\", "
  "\"relationship\".\"target\", "
  "\"relationship\".\"favorite\", "
  "\"relationship\".\"added\" "
  "FROM \"relationship\"";

  const char access::object_traits_impl< ::xle::relationship_record, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"relationship\"";

  const char access::object_traits_impl< ::xle::relationship_record, id_pgsql >::table_name[] =
  "\"relationship\"";

  void access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  persist (database& db, const object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::xle::relationship_record, id_pgsql >::pointer_type
  access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (nullptr);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (nullptr);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (nullptr);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::xle::relationship_record, id_pgsql >::object_type >
  access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  query (database& db, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    std::shared_ptr<select_statement> st (
      std::make_shared<select_statement> (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    std::shared_ptr<odb::object_result_impl<object_type>> r (
      std::make_shared<pgsql::object_result_impl<object_type>> (
        q, std::move (st), sts, nullptr));

    return result<object_type> (std::move (r));
  }

  unsigned long long access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }

  // relationship_entry
  //

  const char access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::
  query_statement_name[] = "query_xle_relationship_entry";

  const char alias_traits<  ::xle::relationship_record,
    id_pgsql,
    access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::forward_tag>::
  table_name[] = "\"forward\"";

  const char alias_traits<  ::xle::relationship_record,
    id_pgsql,
    access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::reverse_tag>::
  table_name[] = "\"reverse\"";

  bool access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // target
    //
    t[0UL] = 0;

    // favorite
    //
    t[1UL] = 0;

    // added
    //
    t[2UL] = 0;

    // following
    //
    t[3UL] = 0;

    return grew;
  }

  void access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // target
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.target_value;
    b[n].is_null = &i.target_null;
    n++;

    // favorite
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.favorite_value;
    b[n].is_null = &i.favorite_null;
    n++;

    // added
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.added_value;
    b[n].is_null = &i.added_null;
    n++;

    // following
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.following_value;
    b[n].is_null = &i.following_null;
    n++;
  }

  void access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // target
    //
    {
      ::xle::xuid& v =
        o.target;

      ::uint64_t vt;

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.target_value,
        i.target_null);

      // From model.hxx:50:12
      v = xle::xuid 
      {
         (vt) 
      };
    }

    // favorite
    //
    {
      bool& v =
        o.favorite;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.favorite_value,
        i.favorite_null);
    }

    // added
    //
    {
      ::xle::timestamp& v =
        o.added;

      ::int64_t vt;

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_value (
        vt,
        i.added_value,
        i.added_null);

      // From model.hxx:58:12
      v = xle::timestamp (std::chrono::duration_cast < xle::duration > (std::chrono::nanoseconds (vt)));
    }

    // following
    //
    {
      bool& v =
        o.following;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.following_value,
        i.following_null);
    }
  }

  access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::query_base_type
  access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::
  query_statement (const query_base_type& q)
  {
    query_base_type r (
      "SELECT "
      "\"forward\".\"target\", "
      "\"forward\".\"favorite\", "
      "\"forward\".\"added\", "
      "(\"reverse\".\"owner\" IS NOT NULL) ");

    r += "FROM \"relationship\" AS \"forward\"";

    r += " LEFT JOIN \"relationship\" AS \"reverse\" ON";
    // From model.hxx:104:5
    r += query_columns::forward::id.target == query_columns::reverse::id.owner && query_columns::forward::id.owner == query_columns::reverse::id.target;

    query_base_type c (
      // From model.hxx:107:5
      (q.empty () ? query_base_type::true_expr : q) + "ORDER BY" + query_columns::forward::added + "," + query_columns::forward::id.target);

    c.optimize ();

    if (!c.empty ())
    {
      r += " ";
      r += c.clause_prefix ();
      r += c;
    }

    return r;
  }

  result< access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::view_type >
  access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::
  query (database& db, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (query_statement (q));
    qs.init_parameters ();
    std::shared_ptr<select_statement> st (
      std::make_shared<select_statement> (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    std::shared_ptr<odb::view_result_impl<view_type>> r (
      std::make_shared<pgsql::view_result_impl<view_type>> (
        qs, std::move (st), sts, nullptr));

    return result<view_type> (std::move (r));
  }

  // relationship_count
  //

  const char access::view_traits_impl< ::xle::relationship_count, id_pgsql >::
  query_statement_name[] = "query_xle_relationship_count";

  bool access::view_traits_impl< ::xle::relationship_count, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // result
    //
    t[0UL] = 0;

    return grew;
  }

  void access::view_traits_impl< ::xle::relationship_count, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // result
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.result_value;
    b[n].is_null = &i.result_null;
    n++;
  }

  void access::view_traits_impl< ::xle::relationship_count, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // result
    //
    {
      ::uint64_t& v =
        o.result;

      pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::set_value (
        v,
        i.result_value,
        i.result_null);
    }
  }

  access::view_traits_impl< ::xle::relationship_count, id_pgsql >::query_base_type
  access::view_traits_impl< ::xle::relationship_count, id_pgsql >::
  query_statement (const query_base_type& q)
  {
    query_base_type r (
      "SELECT "
      "count(*) ");

    r += "FROM \"relationship\"";

    if (!q.empty ())
    {
      r += " ";
      r += q.clause_prefix ();
      r += q;
    }

    return r;
  }

  result< access::view_traits_impl< ::xle::relationship_count, id_pgsql >::view_type >
  access::view_traits_impl< ::xle::relationship_count, id_pgsql >::
  query (database& db, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (query_statement (q));
    qs.init_parameters ();
    std::shared_ptr<select_statement> st (
      std::make_shared<select_statement> (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    std::shared_ptr<odb::view_result_impl<view_type>> r (
      std::make_shared<pgsql::view_result_impl<view_type>> (
        qs, std::move (st), sts, nullptr));

    return result<view_type> (std::move (r));
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"relationship\" CASCADE");
          db.execute ("CREATE TABLE IF NOT EXISTS \"schema_version\" (\n"
                      "  \"name\" TEXT NOT NULL PRIMARY KEY,\n"
                      "  \"version\" BIGINT NOT NULL,\n"
                      "  \"migration\" BOOLEAN NOT NULL)");
          db.execute ("DELETE FROM \"schema_version\"\n"
                      "  WHERE \"name\" = 'xle'");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"relationship\" (\n"
                      "  \"owner\" BIGINT NOT NULL,\n"
                      "  \"target\" BIGINT NOT NULL,\n"
                      "  \"favorite\" BOOLEAN NOT NULL,\n"
                      "  \"added\" BIGINT NOT NULL,\n"
                      "  PRIMARY KEY (\"owner\",\n"
                      "               \"target\"))");
          db.execute ("CREATE INDEX \"relationship_target_i\"\n"
                      "  ON \"relationship\" (\"target\")");
          return true;
        }
        case 2:
        {
          db.execute ("CREATE TABLE IF NOT EXISTS \"schema_version\" (\n"
                      "  \"name\" TEXT NOT NULL PRIMARY KEY,\n"
                      "  \"version\" BIGINT NOT NULL,\n"
                      "  \"migration\" BOOLEAN NOT NULL)");
          db.execute ("INSERT INTO \"schema_version\" (\n"
                      "  \"name\", \"version\", \"migration\")\n"
                      "  SELECT 'xle', 1, FALSE\n"
                      "  WHERE NOT EXISTS (\n"
                      "    SELECT 1 FROM \"schema_version\" WHERE \"name\" = 'xle')");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_pgsql,
    "xle",
    &create_schema);

  static const schema_catalog_migrate_entry
  migrate_schema_entry_1_ (
    id_pgsql,
    "xle",
    1ULL,
    0);
}

#include <odb/post.hxx>
