// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

namespace odb
{
  // relationship_record
  //

  inline
  access::object_traits< ::xle::relationship_record >::id_type
  access::object_traits< ::xle::relationship_record >::
  id (const object_type& o)
  {
    return o.id;
  }

  inline
  void access::object_traits< ::xle::relationship_record >::
  callback (database& db, object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }

  inline
  void access::object_traits< ::xle::relationship_record >::
  callback (database& db, const object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }

  // relationship_entry
  //

  inline
  void access::view_traits< ::xle::relationship_entry >::
  callback (database& db, view_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }

  // relationship_count
  //

  inline
  void access::view_traits< ::xle::relationship_count >::
  callback (database& db, view_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }
}

#include <odb/schema-version.hxx>

namespace odb
{
  // relationship_key
  //

  inline
  bool access::composite_value_traits< ::xle::relationship_key, id_pgsql >::
  get_null (const image_type& i)
  {
    bool r (true);
    r = r && i.owner_null;
    r = r && i.target_null;
    return r;
  }

  inline
  void access::composite_value_traits< ::xle::relationship_key, id_pgsql >::
  set_null (image_type& i,
            pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    i.owner_null = true;
    i.target_null = true;
  }

  // relationship_record
  //

  inline
  void access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  erase (database& db, const object_type& obj)
  {
    callback (db, obj, callback_event::pre_erase);
    erase (db, id (obj));
    callback (db, obj, callback_event::post_erase);
  }

  inline
  void access::object_traits_impl< ::xle::relationship_record, id_pgsql >::
  load_ (statements_type& sts,
         object_type& obj,
         bool)
  {
    ODB_POTENTIALLY_UNUSED (sts);
    ODB_POTENTIALLY_UNUSED (obj);
  }

  // relationship_entry
  //

  // relationship_count
  //
}

