// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef LIBXLE_MODEL_ODB_HXX
#define LIBXLE_MODEL_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20600UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include <libxle/model.hxx>

#include <memory>
#include <cstddef>
#include <utility>
#include <type_traits>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/std-optional-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>
#include <odb/view-image.hxx>
#include <odb/view-result.hxx>

#include <odb/details/unused.hxx>

namespace odb
{
  // relationship_record
  //
  template <>
  struct class_traits< ::xle::relationship_record >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::xle::relationship_record >
  {
    public:
    typedef ::xle::relationship_record object_type;
    typedef ::std::unique_ptr< ::xle::relationship_record > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::xle::relationship_key id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // relationship_entry
  //
  template <>
  struct class_traits< ::xle::relationship_entry >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::xle::relationship_entry >
  {
    public:
    typedef ::xle::relationship_entry view_type;
    typedef ::std::unique_ptr< ::xle::relationship_entry > pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // relationship_count
  //
  template <>
  struct class_traits< ::xle::relationship_count >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::xle::relationship_count >
  {
    public:
    typedef ::xle::relationship_count view_type;
    typedef ::xle::relationship_count* pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // relationship_key
  //
  template <>
  class access::composite_value_traits< ::xle::relationship_key, id_pgsql >
  {
    public:
    typedef ::xle::relationship_key value_type;

    struct image_type
    {
      // owner
      //
      long long owner_value;
      bool owner_null;

      // target
      //
      long long target_value;
      bool target_null;
    };

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static bool
    init (image_type&,
          const value_type&,
          pgsql::statement_kind);

    static void
    init (value_type&,
          const image_type&,
          database*);

    static bool
    get_null (const image_type&);

    static void
    set_null (image_type&,
              pgsql::statement_kind);

    static const std::size_t column_count = 2UL;
  };

  // relationship_record
  //
  template <typename A>
  struct query_columns< ::xle::relationship_record, id_pgsql, A >
  {
    // id
    //
    struct id_class_
    {
      id_class_ ()
      {
      }

      // owner
      //
      typedef
      pgsql::query_column<
        pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::query_type,
        pgsql::id_bigint >
      owner_type_;

      static const owner_type_ owner;

      // target
      //
      typedef
      pgsql::query_column<
        pgsql::value_traits<
          ::uint64_t,
          pgsql::id_bigint >::query_type,
        pgsql::id_bigint >
      target_type_;

      static const target_type_ target;
    };

    static const id_class_ id;

    // favorite
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    favorite_type_;

    static const favorite_type_ favorite;

    // added
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    added_type_;

    static const added_type_ added;
  };

  template <typename A>
  const typename query_columns< ::xle::relationship_record, id_pgsql, A >::id_class_::owner_type_
  query_columns< ::xle::relationship_record, id_pgsql, A >::id_class_::
  owner (A::table_name, "\"owner\"", 0);

  template <typename A>
  const typename query_columns< ::xle::relationship_record, id_pgsql, A >::id_class_::target_type_
  query_columns< ::xle::relationship_record, id_pgsql, A >::id_class_::
  target (A::table_name, "\"target\"", 0);

  template <typename A>
  const typename query_columns< ::xle::relationship_record, id_pgsql, A >::id_class_
  query_columns< ::xle::relationship_record, id_pgsql, A >::id;

  template <typename A>
  const typename query_columns< ::xle::relationship_record, id_pgsql, A >::favorite_type_
  query_columns< ::xle::relationship_record, id_pgsql, A >::
  favorite (A::table_name, "\"favorite\"", 0);

  template <typename A>
  const typename query_columns< ::xle::relationship_record, id_pgsql, A >::added_type_
  query_columns< ::xle::relationship_record, id_pgsql, A >::
  added (A::table_name, "\"added\"", 0);

  template <typename A>
  struct pointer_query_columns< ::xle::relationship_record, id_pgsql, A >:
    query_columns< ::xle::relationship_record, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::xle::relationship_record, id_pgsql >:
    public access::object_traits< ::xle::relationship_record >
  {
    public:
    struct id_image_type
    {
      composite_value_traits< ::xle::relationship_key, id_pgsql >::image_type id_value;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      composite_value_traits< ::xle::relationship_key, id_pgsql >::image_type id_value;

      // favorite
      //
      bool favorite_value;
      bool favorite_null;

      // added
      //
      long long added_value;
      bool added_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 2UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    static const std::size_t batch = 1UL;

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::xle::relationship_record, id_common >:
    public access::object_traits_impl< ::xle::relationship_record, id_pgsql >
  {
  };

  // relationship_entry
  //
  template <>
  class access::view_traits_impl< ::xle::relationship_entry, id_pgsql >:
    public access::view_traits< ::xle::relationship_entry >
  {
    public:
    struct image_type
    {
      // target
      //
      long long target_value;
      bool target_null;

      // favorite
      //
      bool favorite_value;
      bool favorite_null;

      // added
      //
      long long added_value;
      bool added_null;

      // following
      //
      bool following_value;
      bool following_null;

      std::size_t version;
    };

    typedef pgsql::view_statements<view_type> statements_type;

    struct forward_tag;
    struct reverse_tag;

    typedef pgsql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 4UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);

    static const char query_statement_name[];
  };

  template <>
  class access::view_traits_impl< ::xle::relationship_entry, id_common >:
    public access::view_traits_impl< ::xle::relationship_entry, id_pgsql >
  {
  };

  // relationship_count
  //
  template <>
  class access::view_traits_impl< ::xle::relationship_count, id_pgsql >:
    public access::view_traits< ::xle::relationship_count >
  {
    public:
    struct image_type
    {
      // result
      //
      long long result_value;
      bool result_null;

      std::size_t version;
    };

    typedef pgsql::view_statements<view_type> statements_type;

    typedef pgsql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 1UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);

    static const char query_statement_name[];
  };

  template <>
  class access::view_traits_impl< ::xle::relationship_count, id_common >:
    public access::view_traits_impl< ::xle::relationship_count, id_pgsql >
  {
  };

  // relationship_record
  //
  // relationship_entry
  //
  template <>
  struct alias_traits<
    ::xle::relationship_record,
    id_pgsql,
    access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::forward_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::xle::relationship_record,
    id_pgsql,
    access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::reverse_tag>
  {
    static const char table_name[];
  };

  struct access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::query_columns
  {
    // forward
    //
    typedef
    odb::pointer_query_columns<
      ::xle::relationship_record,
      id_pgsql,
      odb::alias_traits< ::xle::relationship_record,
        id_pgsql,
        access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::forward_tag> >
    forward;

    // reverse
    //
    typedef
    odb::pointer_query_columns<
      ::xle::relationship_record,
      id_pgsql,
      odb::alias_traits< ::xle::relationship_record,
        id_pgsql,
        access::view_traits_impl< ::xle::relationship_entry, id_pgsql >::reverse_tag> >
    reverse;
  };

  // relationship_count
  //
  struct access::view_traits_impl< ::xle::relationship_count, id_pgsql >::query_columns:
    odb::pointer_query_columns<
      ::xle::relationship_record,
      id_pgsql,
      odb::access::object_traits_impl< ::xle::relationship_record, id_pgsql > >
  {
  };
}

#include <libxle/model-odb.ixx>

#include <odb/post.hxx>

#endif // LIBXLE_MODEL_ODB_HXX
