# Copyright (c) the IW4x authors (see the AUTHORS file).
# SPDX-License-Identifier: GPL-3.0-only WITH AdditionRef-IW4x-Exception-1.1

import libs = libxle%lib{xle}
import libs += libboost-asio%lib{boost_asio}

exe{driver}: {hxx ixx txx cxx}{**} $libs testscript
