# Copyright (c) the IW4x authors (see the AUTHORS file).
# SPDX-License-Identifier: GPL-3.0-only WITH AdditionRef-IW4x-Exception-1.1

./: file{** -buildfile}

# Install into the etc/ subdirectory of, say, /usr/share/ recreating
# subdirectories.
#
*:
{
  install         = data/etc/
  install.subdirs = true
}

# Keep the executable permission for the installed script files.
#
private/postgresql/
{
  file{xle-postgresql-setup}@./: install.mode=755
}
