# Copyright (c) the IW4x authors (see the AUTHORS file).
# SPDX-License-Identifier: GPL-3.0-only WITH AdditionRef-IW4x-Exception-1.1

import libs  = libxle%lib{xle}
import libs += libboost-asio%lib{boost_asio}

# Note that store.testscript is included by testscript (rather than being a
# test of its own).
#
exe{driver}: {hxx ixx txx cxx}{**} $libs testscript file{store.testscript}
